#!/bin/bash
# formats zdc_pol_table.txt by filtering out text columns

infile="zdc_pol_table.txt"
outfile="zdc_pol_table_formatted.txt"
> $outfile

cat goodruns.dat | awk '{print $1}' > runlist

i=0
while read line; do
  str=$(echo $line | sed \
  's/yellow //g;s/blue //g;s/forward //g;s/backward //g;s/asymmetry //g;s/polarization //g;s/analyzingpower //g;s/anglevertical //g')
  grepstr=$(grep $(echo $str | awk '{print $2}') runlist)
  fill=$(echo $str | awk '{print $1}')
  if [ $fill -eq 16570 -o $fill -eq 16578 ]; then
    grepstr="t" # force run 12 transverse runs into tree
  fi
  #grepstr="a" # OVERRIDE ALL
  if [ -n "$grepstr" ]; then
    echo $i $str >> $outfile
    let i++
  fi
done < $infile

rm runlist
